version: '3'
services:
  app:
    image: idpinjar:latest
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    #必ず本番環境ではDBのパスワードは変更すること
    environment:
      DBACCOUNT: ""
      DBPASSWORD: ""
      DB_URL: ""
      REDIS_URL: ""
      MINIMUM_PASS: ""
      MAIL_ADDRESS: ""
      MAIL_PASS: ""
      SELF_URL: "http://localhost:3000"
      LOGIN_URL: "http://localhost:3000/login"
      UPLOADER_SECRET: ""
      IDTOKEN_VALID_TIME_MINUTE: "5"
    command: java -jar target/IdP-1.0-all.jar
  db:
    image: mariadb:latest
    #必ず本番環境ではDBのパスワードは変更すること
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: den3_account
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes: # ← Volumesでデータ領域をコンテナとして定義
  mariadb:
    driver: local